[profile.default]
src = 'contracts'
exclude = ["contracts/node_modules"]
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "./"}]
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

solc_version = "0.8.27"
evm_version = "paris"

optimizer = true
## optimizer-runs = 1
